#!url=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Shadowrocket/blued.module
#!name= Blued闪照
#!desc= Blued闪照转通知

[Script]
blued = type=http-response,pattern=^https:\/\/.*burn-chatfiles\.bldimg\.com\/,requires-body=1,max-size=3145728,script-path=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Scripts/Blued/blued.js,script-update-interval=0

[MITM]
hostname = %APPEND% *burn-chatfiles.bldimg.com