#!url=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Shadowrocket/blued.module
#!name= Blued闪照
#!desc= Blued闪照转通知

[Script]
Blued闪照 = type=http-response,pattern=^https:\/\/(www|burn-chatfiles)\.bldimg\.com\/(ingfiles|burn_chatfiles\/(videos|users))\/.*(mp4|jpg|(jpg|png)).*,requires-body=0,max-size=0,debug=0,script-path=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Scripts/Blued/blued.js,script-update-interval=0

[MITM]
hostname = %APPEND% *burn-chatfiles.bldimg.com