#!url=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Shadowrocket/qing.save.module
#!name= Qing闪照保存
#!desc= Qing闪照转快捷指令保存
#!category=HerbertGao's Scripts

[Script]
Qing闪照保存① = type=http-response,pattern=^https?:\/\/cdn\.qing2000\.com\/private-flash-photo\/.*,requires-body=0,max-size=0,debug=0,script-path=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Scripts/Qing/qing.save.js,script-update-interval=0

[MITM]
hostname = %APPEND% cdn.qing2000.com
