hostname = *burn-chatfiles.bldimg.com, *burn-chatfiles.bldimg.cn, argo.blued.cn, social.blued.cn, voice.irisgw.cn

# 广告拦截规则
^https://argo\.blued\.cn/blued/promote.* url reject
^https://argo\.blued\.cn/blued/adms/.* url reject
^https://argo\.blued\.cn/blued/splash.* url reject
^https://argo\.blued\.cn/blued/launch/adms url reject
^https://social\.blued\.cn/users/.*/joy url reject
^https://social\.blued\.cn/users/recommend url reject
^https://voice\.irisgw\.cn/users/chatroom url reject

# Blued闪照脚本
^https:\/\/(burn-chatfiles)\.bldimg\.(com|cn)\/.*\/(ingfiles|burn_chatfiles\/(videos|users))\/.* url script-response-body https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Scripts/Blued/blued.js