hostname = *burn-chatfiles.bldimg.com, *burn-chatfiles.bldimg.cn

^https:\/\/(burn-chatfiles)\.bldimg\.(com|cn)\/.*\/(ingfiles|burn_chatfiles\/(videos|users))\/.*\.(mp4|jpg|png).* url script-response-body https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Scripts/Blued/blued.js