hostname = cdn.qing2000.com

# Qing闪照保存①
^https?:\/\/cdn\.qing2000\.com\/private-flash-photo\/.* url script-response-body https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Scripts/Qing/qing.save.js
