hostname = shengmo2.oss-cn-shanghai.aliyuncs.com, image.oss2.aiwujie.com.cn

# 圣魔闪照保存①
^http:\/\/shengmo2\.oss-cn-shanghai\.aliyuncs\.com\/Uploads\/Fastphoto\/ url script-response-body https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Scripts/Shengmo/shengmo.save.js
# 圣魔闪照保存②
^https?:\/\/image\.oss2\.aiwujie\.com\.cn\/Uploads\/Fastphoto\/ url script-response-body https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Scripts/Shengmo/shengmo.save.js
