GET /burn_chatfiles/users/59630780/59630780_1658366371525_53392.jpg!o.png?e=1658971172&token=wmjGqfw_bFxJViEa3Aqf3Io0X0e4JMZvDKmNCE54:89cSCetveqH_Q3exDaLDSbqU_fI= HTTP/1.1
Host: burn-chatfiles.bldimg.com
Accept: image/*,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh-Hans;q=0.9
Connection: keep-alive
User-Agent: Blued/7.14.6 (iPhone; iOS 16.2; Scale/3.00)