#!url=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Surge/fix-vvebo.module
#!name= 修复 VVebo
#!desc= 修复 VVebo 用户时间线

[Script]
fix-vvebo-user-timeline = type=http-request,pattern=^https:\/\/api\.weibo\.cn\/2\/users\/show\?,script-path=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Scripts/Vvebo/fix-vvebo-user-timeline.js,script-update-interval=0
fix-vvebo-user-timeline = type=http-request,pattern=^https:\/\/api\.weibo\.cn\/2\/statuses\/user_timeline\?,script-path=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Scripts/Vvebo/fix-vvebo-user-timeline.js,script-update-interval=0
fix-vvebo-user-timeline = type=http-response,pattern=^https:\/\/api\.weibo\.cn\/2\/profile\/statuses\/tab\?,requires-body=1,max-size=307200,script-path=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Scripts/Vvebo/fix-vvebo-user-timeline.js,script-update-interval=0

[MITM]
hostname = %APPEND% api.weibo.cn