#!url=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Surge/friend-confession.module
#!name= 朋友坦白局
#!desc= 朋友坦白局回复解析
#!category=HerbertGao's Scripts

[Script]
朋友坦白局 = type=http-response,pattern=^http:\/\/t3\.haoyouxiaozhitiao\.top\/h5friend\/archive\?id=.*&mid=.*,requires-body=1,max-size=0,debug=0,script-path=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Scripts/FriendConfession/friend-confession.js,script-update-interval=0

[MITM]
hostname = %APPEND% t3.haoyouxiaozhitiao.top