#!url=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Surge/muscle-booster.module
#!name= Muscle Booster
#!desc= Muscle Booster内购破解
#!category=HerbertGao's Scripts

[Script]
Muscle Booster = type=http-response, pattern=^https:\/\/menscoach-api.asqq.io\/prod\/(user|check-receipt|subscription-restore),requires-body=1,max-size=0,debug=0,script-path=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Surge/muscle-booster.module

[MITM]
hostname = *menscoach*