#!url=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Surge/shengmo.save.module
#!name= 圣魔 闪照保存
#!desc= 圣魔 闪照转快捷指令保存
#!category=HerbertGao's Scripts

[Script]
shengmo保存① = type=http-response,pattern=^http:\/\/shengmo2\.oss-cn-shanghai\.aliyuncs\.com\/Uploads\/Fastphoto\/,requires-body=0,max-size=0,debug=0,script-path=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Scripts/Shengmo/shengmo.save.js,script-update-interval=0
shengmo保存② = type=http-response,pattern=^https?:\/\/image\.oss2\.aiwujie\.com\.cn\/Uploads\/Fastphoto\/,requires-body=0,max-size=0,debug=0,script-path=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Scripts/Shengmo/shengmo.save.js,script-update-interval=0

[MITM]
hostname = %APPEND% shengmo2.oss-cn-shanghai.aliyuncs.com, image.oss2.aiwujie.com.cn
