#!url=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Surge/shengmo.module
#!name= 圣魔 闪照
#!desc= 圣魔 闪照转通知

[Script]
shengmo = type=http-response,pattern=^http:\/\/shengmo2\.\w+\.aliyuncs\.com\/Uploads\/Fastphoto\/,requires-body=1,max-size=31457280,script-path=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Scripts/Shengmo/shengmo.js,script-update-interval=0

[MITM]
hostname = %APPEND% shengmo2.oss-cn-shanghai.aliyuncs.com