#!url=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Surge/subapp.module
#!name= SubApp阅后即焚
#!desc= SubApp阅后即焚转通知
#!category=HerbertGao's Scripts

[Script]
subapp = type=http-response,pattern=^http:\/\/rongcloud-spic\.ronghub\.com\/,requires-body=0,max-size=0,debug=0,script-path=https://raw.githubusercontent.com/HerbertGao/Scripts/dev/Scripts/SubApp/subapp.js,script-update-interval=0

[MITM]
hostname = %APPEND% rongcloud-spic.ronghub.com